# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.nongnu.org/nongnu/"
SOURCE_TYPE="tar"
REALNAME="evil-collection"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="A set of keybindings for Evil mode"

HOMEPAGE="https://github.com/emacs-evil/evil-collection"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/evil"
RDEPEND="app-emacs/evil"
