# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.nongnu.org/nongnu/"
SOURCE_TYPE="tar"
REALNAME="hermes"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Emacs frontend for Hermes Agent"

HOMEPAGE="https://git.thanosapollo.org/emacs-hermes"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/keymap-popup
	app-emacs/websocket
	app-emacs/markdown-mode"
RDEPEND="app-emacs/keymap-popup
	app-emacs/websocket
	app-emacs/markdown-mode"
