# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.nongnu.org/nongnu/"
SOURCE_TYPE="tar"
REALNAME="eldoc-mouse-nov"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Preview epub link for mouse hover"

HOMEPAGE="https://github.com/huangfeiyu/eldoc-mouse-nov"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/eldoc-mouse
	app-emacs/nov"
RDEPEND="app-emacs/eldoc-mouse
	app-emacs/nov"
