# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.nongnu.org/nongnu/"
SOURCE_TYPE="tar"
REALNAME="project-nix-store"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Project backend for Nix-like store"

HOMEPAGE="https://github.com/jian-lin/project-nix-store"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
