# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.nongnu.org/nongnu/"
SOURCE_TYPE="tar"
REALNAME="vm"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="VM mail reader"

HOMEPAGE="https://gitlab.com/emacs-vm/vm"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/vcard"
RDEPEND="app-emacs/vcard"
