# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.nongnu.org/nongnu/"
SOURCE_TYPE="tar"
REALNAME="codex-ide"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Run Codex CLI in a terminal"

HOMEPAGE="https://git.thanosapollo.org/emacs-codex-ide"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/compat
	app-emacs/keymap-popup
	app-emacs/eat"
RDEPEND="app-emacs/compat
	app-emacs/keymap-popup
	app-emacs/eat"
